### PR TITLE
Refactor the "Prefix" class to "Flag", and update the defaults to match the Unix-like syntax "--flag"

### LINKED ISSUE #16: Update command argument syntax to use `--` prefix instead of `/` postfix
We should update our command argument syntax to use something similar to CLI programs on Unix: `--argument value` (instead of the existing  `a/value`).

This makes it so that it is much less likely to conflict with user input, and as such we can use an arbitrary length argument name for disambiguation instead of a bunch of obscure one letter mappings. For faster typing, shorthand versions could be implemented in future updates in the form of `-a value` or something similar.

### PR DESCRIPTION
**Pull request by wxwern**
The renaming is primarily done because it may conflict with future prefix-matching functionality planned. This also makes the class use a common name for easier understanding (it is commonly called a command-line option, flag, or switch).

The refactor also includes some improvements in internal structure to allow for flexible syntax changes.

The update of the syntax (e.g., from `n/`) to the Unix-like variant (e.g., to `--name`) closes #16.

---

Note: The existing code does not require a whitespace between flags though, which may be confusing since something like `--nameAlice` could be accepted. This will be addressed in a separate PR to revamp the argument parsing.

### CODE REVIEW

**Review by tanshiyu1999 — APPROVED** [review]
LGTM

**Review by wamps-jp — APPROVED** [review]
Should be fine for now!

**Review by McNaBry — COMMENTED** [review]
Verified changes to parser works for add and edit. Since Prefix is being refactored to flags, do we want to change all mentions of prefixes to flags similar to the person -> contact refactor?

**Comment by wxwern** [comment]
> Since Prefix is being refactored to flags, do we want to change all mentions of prefixes to flags similar to the person -> contact refactor?

Yeah, I missed a few and have fixed them in the latest commit.

**Review by McNaBry — APPROVED** [review]
Ok the refactor seems to have changed any mentions of the old Prefix class in the source code. Overall, looks good to me.

**Pull request merged**
