### PR TITLE
Add terms to glossary

### PR DESCRIPTION
**Pull request by CJ-Lee01**
~~Added non-functional requirements to the NFR list for command syntax and argument syntax.~~ (removed as they aren't exactly NFRs)

Added the definition for commands and arguments in the glossary.

### CODE REVIEW

**Comment by wxwern** [comment]
Based on our tutorials, specific requirements of the command might not qualify as NFRs... perhaps others can provide some input on the matter.

**Comment by McNaBry** [comment]
> Based on our tutorials, specific requirements of the command might not qualify as NFRs... perhaps others can provide some input on the matter.

Hm yeah I feel that command syntax requirements would be a functional requirement since its a must-have for the program we are developing? Although we could phrase it as a NFR by saying "commands should be short and simple enough, limited to around 10 characters for better user experience"

**Comment by CJ-Lee01** [comment]
Since this is confusing I'll just remove all the syntax NFR and keep the glossary.

**Review by McNaBry — APPROVED** [review]
Overall, looks good to me

**Pull request merged**
