### PR TITLE
Add UI for applications

### PR DESCRIPTION
**Pull request by CJ-Lee01**
This was a mess to do.

There is the bug of application list not updating after adding new applications.

### CODE REVIEW

**Comment by CJ-Lee01** [comment]
Also did a few significant refactoring

**Comment by CJ-Lee01** [comment]
Bug has been fixed.

**Comment by CJ-Lee01** [comment]
:(

**Review by McNaBry — APPROVED** [review]
Overall looks good to me. Sorting of job applications is not complete but can be addressed at a later stage.

**Pull request merged**
