### PR TITLE
Add Command Summary tables

### PR DESCRIPTION
**Pull request by wamps-jp**
Added Command Summary tables for handling contacts, applications, and other commands.

https://wamps-jp.github.io/tp/UserGuide.html#command-summary

### CODE REVIEW

**Comment by wamps-jp** [comment]
Don't merge yet, still need thoughts on the formatting.

**Comment by McNaBry** [comment]
> Don't merge yet, still need thoughts on the formatting.

Is the formatting still in progress?

**Comment by CJ-Lee01** [comment]
> `add --org --name <NAME> ...`

omit the <>.

**Comment by CJ-Lee01** [comment]
> `delete --application INDEX/ID`

Currently delete application only supports index.

**Comment by CJ-Lee01** [comment]
is the `...` in the edit commands explained?

**Comment by CJ-Lee01** [comment]
Find command should be moved under Contacts since find is not supported for applications

**Comment by CJ-Lee01** [comment]
> `list [--org/--rec]`

what happened to `list --toapply`?

**Comment by wamps-jp** [comment]
> > `list [--org/--rec]`
> 
> what happened to `list --toapply`?

`list --toapply` is not supported, given the two column approach.
The list of applications will always be shown in full - if you want to change how the applications are shown, `sort` is the applicable command.

**Comment by wamps-jp** [comment]
> Find command should be moved under Contacts since find is not supported for applications

Thanks for the heads up, was unsure of that.

**Comment by wamps-jp** [comment]
> is the `...` in the edit commands explained?

Let me check. I believed it was something shown in the command explanation section, although I can be more specific.

**Comment by McNaBry** [comment]
> > is the `...` in the edit commands explained?
> 
> Let me check. I believed it was something shown in the command explanation section, although I can be more specific.

I think it would be good to just include all the parameters into edit? aka just copy paste the entire format in

**Comment by McNaBry** [comment]
Also as a minor thing, could change **List** to **List Contacts** and **Find** to **Find Contacts**

**Review by McNaBry — APPROVED** [review]
Tables looks good to me.

**Pull request merged**
