### PR TITLE
Fix sorting for JsonSerializableAddressBook to preserve Org-Rec hierarchy

### PR DESCRIPTION
**Pull request by McNaBry**

### CODE REVIEW

**Comment by CJ-Lee01** [comment]
will this violate feature freeze?

**Comment by McNaBry** [comment]
> will this violate feature freeze?

Hm. This sorting was to handle the case where someone directly tampered with the storage and swapped the recruiter to be before its linked organization.

I would say its fixing a bug? Since the contacts are already sorted being written to storage

**Review by wxwern — APPROVED** [review]
LGTM

**Comment by wxwern** [comment]
> Since the contacts are already sorted being written to storage 

Yep, due to this I'd say it's a bug. The existing code relies on the assumption that contacts are sorted in a certain order, and the app will break if that assumption is not true.

**Comment by wxwern** [comment]
To limit the likelihood of being considered to break feature freeze, perhaps we could sort it back to the original database order after we're done loading all `Contact` instances.

**Comment by McNaBry** [comment]
Might not be the best way to solve this, however in lieu of feature freeze and limited time, the current solution is proposed.

Retrieve the JsonAdaptedContacts from storage, map each of their unique Ids to an Integer which preserves the order in which they were stored.

Sort the list and convert each JsonAdaptedContact to the Contact via toModelType
Sort this new list of contactswith the original comparator which references the map
Set the addressbook with this list of contacts

**Review by wxwern — APPROVED** [review]

**Pull request merged**
