### PR TITLE
Add appendix for acceptable parameter values and glossary in UG

### PR DESCRIPTION
**Pull request by McNaBry**
https://mcnabry.github.io/tp/UserGuide.html#glossary

Do check whether:
- All parameters have been added into the table
- Their requirements are understandable and are correct
- The examples given are sufficient and correct
- The use of code tags and bold are CONSISTENT and valid

### CODE REVIEW

**Comment by CJ-Lee01** [comment]
> A valid index can accept any non-negative integer.

Should be more specific. Non-negative integer can also mean 0 but 0 is invalid.

A valid index can accept any positive integer up to the number of items in the contact or job application list where applicable.

**Comment by CJ-Lee01** [comment]
> A valid ID has to start with a letter.
> It can consists of alphanumeric and basic symbols

Grammar: It can _consist_ of ....

**Comment by CJ-Lee01** [comment]
> A valid phone number can consist of only numbers with no whitespace.

May need to add whitespace to glossary.

**Comment by CJ-Lee01** [comment]
> `list [--org/--rec]`

what happened to `list --toapply`?

**Comment by McNaBry** [comment]
> > `list [--org/--rec]`
> 
> what happened to `list --toapply`?
This isn't covered in the scope of this PR. Should be directed to @wamps-jp instead

**Comment by CJ-Lee01** [comment]
> > > `list [--org/--rec]`
> > 
> > 
> > what happened to `list --toapply`?
> 
> This isn't covered in the scope of this PR. Should be directed to @wamps-jp instead

my bad i commented on the wrong PR

**Comment by CJ-Lee01** [comment]
Title is not included

**Comment by CJ-Lee01** [comment]
KEYWORD from the find command is also not inside

**Comment by CJ-Lee01** [comment]
image
which one shld we use for OID?

**Comment by CJ-Lee01** [comment]
maybe shld change `APPLICATION STAGE` to just `STAGE`

**Comment by McNaBry** [comment]
> Title is not included

Ok will include.

> KEYWORD from the find command is also not inside

Ok will include.

> maybe shld change `APPLICATION STAGE` to just `STAGE`

We standardise. So just APPLICATION STAGE.

**Pull request merged**
