### PR TITLE
Refactor person to contact

### PR DESCRIPTION
**Pull request by CJ-Lee01**
Updated a few test cases and documentation to reflect the change and changed `toString` method to pass test cases.

### CODE REVIEW

**Comment by CJ-Lee01** [comment]
It appears that the JsonSerializableAddressBook class cannot be refactored without breaking a lot of things.

**Comment by wxwern** [comment]
> It appears that the JsonSerializableAddressBook class cannot be refactored without breaking a lot of things.

I believe this is because that class (and other similar ones) functions as the interface between the final JSON file stored and the internal models, converting to and from via Jackson. Since many tests use template JSON files to verify JSON Serializable class behaviors, all JSON test cases must be manually modified and likely cannot be automatically refactored by the IDE.

**Review by McNaBry — APPROVED** [review]
Overall looks good to me. The changes pass the tests on my side as well.

**Review by wamps-jp — APPROVED** [review]
Looks okay. We may need to change the name of the person package to contact later on, but for now it should be fine!

**Pull request merged**
