### PR TITLE
Changed ShiYu Info to specification

### PR DESCRIPTION
**Pull request by tanshiyu1999**

### CODE REVIEW

**Comment by CJ-Lee01** [comment]
Commit message does not follow commit style: [Use imperative mood](https://se-education.org/guides/conventions/git.html).

Should be `Change ShiYu info to specification`

May have to open a new PR for this.

**Comment by wxwern** [comment]
To fix the commit message, you may simply amend your commit and do a force push on your own master branch - it'll automatically update in the PR here

**Review by wxwern — CHANGES_REQUESTED** [review]
Do rewrite the commit message to be in the imperative mood.

**Review by CJ-Lee01 — APPROVED** [review]
Looks good to me.

**Pull request merged**
